#项目服务器配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://121.43.185.118/db_share?useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root_wrj
      password: wangruijiang123W@
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000

  data:
    redis:
      host: 127.0.0.1
      password:
      port: 6379